// PLACEHOLDER / LISTA REPRESENTATIVA — revisar y editar.
// Esta lista refleja aseguradoras comúnmente aceptadas por clínicas de terapia
// física, quiropráctica y acupuntura en el área de Nueva York. NO confirma que
// Corona Hands-On Therapy tenga contrato vigente con cada una — antes de
// publicar, confirma con el equipo de billing cuáles se aceptan realmente,
// y ajusta esta lista para que sea 100% precisa.

export const INSURANCE_CATEGORIES: { category: string; plans: string[] }[] = [
  {
    category: "Major Medical & Health Insurance Plans",
    plans: [
      "Aetna",
      "Cigna",
      "UnitedHealthcare",
      "Empire BlueCross BlueShield",
      "Oxford Health Plans",
      "EmblemHealth / GHI",
      "Fidelis Care",
      "MetroPlus Health Plan",
      "Healthfirst",
      "Oscar Health",
      "WellCare",
      "Amerigroup",
      "Affinity Health Plan",
      "VNS Health Plans",
      "MVP Health Care",
      "Excellus BlueCross BlueShield",
      "Independent Health",
      "HealthNow New York",
      "1199SEIU Benefit and Pension Funds",
      "District Council 37 (DC 37) Health Fund",
      "UFT Welfare Fund",
      "Teamsters Health & Welfare Fund",
      "Medicare",
      "Medicare Advantage (all major carriers)",
      "Medicaid Managed Care (NY State)",
      "Tricare / Tricare for Life",
      "Cigna Healthspring",
      "Anthem BlueCross BlueShield",
      "Humana",
      "Molina Healthcare",
      "Centene / New York State of Health plans",
      "GHI CBP (City of New York employees)",
      "Local 1199 Union Plan",
      "NYSHIP (New York State Health Insurance Program)",
      "Freelancers Union Health Plan",
      "ConnectiCare",
      "Health Republic (legacy plans)",
      "Aetna Better Health of New York",
      "UnitedHealthcare Community Plan",
      "Elderplan",
    ],
  },
  {
    category: "Auto Insurance Carriers",
    plans: [
      "GEICO",
      "State Farm",
      "Progressive",
      "Allstate",
      "Liberty Mutual",
      "Travelers",
      "Nationwide",
      "Farmers Insurance",
      "USAA",
      "MetLife Auto & Home",
      "NJM Insurance Group",
      "Plymouth Rock Assurance",
      "Kemper",
      "Mercury Insurance",
      "American Family Insurance",
      "21st Century Insurance",
      "Esurance",
      "Safeco Insurance",
      "The General",
      "Root Insurance",
      "Erie Insurance",
      "AAA Insurance",
      "Amica Mutual Insurance",
      "Country Financial",
      "Hanover Insurance",
      "National General Insurance",
      "Direct Auto Insurance",
      "Infinity Auto Insurance",
      "Dairyland Insurance",
      "Bristol West Insurance",
      "Elephant Insurance",
      "Clearcover",
      "MAPFRE Insurance",
      "New York Central Mutual",
      "Adirondack Insurance Exchange",
      "Utica National Insurance",
      "Interboro Insurance",
      "Global Liberty Insurance",
      "Ameriprise Auto & Home",
      "Encompass Insurance",
    ],
  },
  {
    category: "Work-Related Injury Insurance Carriers",
    plans: [
      "New York State Insurance Fund (NYSIF)",
      "Travelers",
      "The Hartford",
      "Zurich American Insurance",
      "AIG",
      "Chubb",
      "Liberty Mutual",
      "Berkshire Hathaway GUARD Insurance",
      "AmTrust Financial",
      "ICW Group",
      "Employers Holdings",
      "Encova Insurance",
      "SAIF Corporation",
      "Pinnacol Assurance",
      "Texas Mutual Insurance",
      "Sentry Insurance",
      "Zenith Insurance",
      "Star Insurance Company",
      "Utica National",
      "Security National Insurance",
      "Ohio Casualty",
      "Great American Insurance",
      "CNA Insurance",
      "Nationwide Mutual",
      "Selective Insurance",
      "Cincinnati Insurance",
      "Old Republic Insurance",
      "American Zurich Insurance",
      "Arch Insurance Group",
      "Markel Corporation",
      "ProAssurance",
    ],
  },
];

export const TOTAL_INSURANCE_COUNT = INSURANCE_CATEGORIES.reduce(
  (sum, c) => sum + c.plans.length,
  0
);
